ats/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"   


urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path('newticket',views.NewTicket.as_view(),name = 'new_ticket'),
    path('ticket/<int:pk>',views.TicketDetailView.as_view(),name='ticket_details'),
    path('article/edit/<int:pk>',views.EditTicketView.as_view(),name = 'edit_ticket'),
    path('article/delete/<int:pk>',views.DeleteTicketView.as_view(),name = 'delete_ticket'),
    path("logout", views.logout_request, name="logout")
]



main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Tickets(models.Model):
    name = models.CharField(max_length=255,default=None)
    description = models.TextField(default=None)
    author  = models.ForeignKey(User,models.CASCADE)
    is_updated_by_admin = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    is_updated = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:homepage')


main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Tickets

# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


class TicketEditForm(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = ['name', 'description']

class TicketForm(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = '__all__'

main/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm, TicketEditForm, TicketForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Tickets
from django.urls import reverse_lazy
from django.db.models import F, Value


# def home(request):
#     return render(request=request, template_name="header.html")

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("main:homepage")


class HomeView(ListView):
    model = Tickets
    template_name = 'header.html'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context

class TicketDetailView(DetailView):
    model = Tickets
    template_name = 'ticket_view.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Tickets.objects.all()
        context = super(TicketDetailView,self).get_context_data(*args, **kwargs)
        context['ticket'] = cat_menu
        return context

class EditTicketView(UpdateView):
    model = Tickets
    form_class = TicketEditForm
    # fields = ['title','body']
    template_name = 'update_ticket.html'
    def form_valid(self, form):
        # form.instance.owner = self.request.user
        # ry :
		# 	print(form.instance)t
        try :
            if self.request.user.is_superuser :
                # print(form.instance.is_deleted)
                form.instance.is_updated = True 
                form.instance.is_updated_by_admin = True
            else : 
                form.instance.is_updated = False 
                form.instance.is_updated_by_admin = True
        except Exception as e:
            print('Exception OCcured', e)
        return super().form_valid(form)

class DeleteTicketView(DeleteView):
    model = Tickets
    template_name = 'delete_ticket.html'
    success_url = reverse_lazy('main:homepage')
	
    # def form_valid(self, form) :
    #     # print(form.instance.author_id)
    #     if self.request.user.is_superuser and not form.instance.is_deleted :
    #         print('Inside delete super user')
    #         form.instance.is_deleted = True 
    #         form.instance.is_updated_by_admin = True
    #         form.save()
    #     elif form.instance.is_deleted :
    #         return super().form_valid(form)
    #     else :
    #         return  super().form_valid(form)


		# model  = Tickets.objects.all()


class NewTicket(CreateView):
    model = Tickets
    form_class = TicketForm
    template_name = 'add_ticket.html'

main/templates/add_ticket.html
{% extends 'header.html'%}

{% block title %}
Create New Ticket
{% endblock %}

{% block content %}
<h1>Add Ticket</h1>
{% if user.is_authenticated %}
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">Save</button>
    </form>
</div>
<script>
    $('#id_author').val("{{ user.pk }}")
    $('#id_author').parents('p').first().hide()
    $('#id_is_updated_by_admin').parents('p').first().hide()
    $('#id_is_deleted').parents('p').first().hide()
    $('#id_is_updated').parents('p').first().hide()
</script>
{%else%}
<div>
    <p>Please Login or Register to add a post.</p>
</div>
{% endif %}
{% endblock %}

main/templates/delete_ticket.html
{% extends 'header.html'%}

{% block title %}
Delete Ticket | {{object.name}}
{% endblock %}

{% block content %}
<h1>Delete Ticket</h1>
<br>
<br>
{% if user.is_authenticated %}
<h2>Delete Ticket : {{object.name}} </h2>
{% if object.author.pk == user.pk or user.is_superuser %}
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <b>Are you sure you Want to Delete</b><br>
            <button class="btn btn-secondary">Delete Ticket</button>
        </form>
    </div>
{% else %}
    <p> You Are not the author</p>
{% endif %}
{% else %}
<div>
    <p>You need to be signed in or registered for this.</p>
</div>
{% endif %}
{% endblock %}

main/templates/header.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.6.2.min.js" integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA=" crossorigin="anonymous"></script>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>
    {% block title %}
    Welcome To ATS!
    {% endblock %}
  </title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">ATS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:new_ticket' %}">Create Ticket</a>
      </li>
      <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'main:login' %}">Login</a>
      </li>
      <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'main:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>
    </div>
  </nav>
  <br>
  <div class="container">
    {% block content %}
    {% if user.is_authenticated or user.is_superuser %}
    <ul>
      <!-- Iterate over object_list -->
      {% for object in object_list %}
      <!-- Display Objects -->
      <li>{{ object.name }}</li>
      <li>{{ object.description }}</li>
      {% if object.is_updated_by_admin  and object.is_updated %} 
      <li> It is updated by Admin</li>
      {% endif %}
      {% if object.is_updated_by_admin  and object.is_deleted %} 
      <li> It is Deleted by Admin, You Should Also Delete It</li>
      {% endif %}
      
      <li>
        <button class="button">
          <a href="{% url 'main:ticket_details' object.pk %}">VIEW</a>
        </button>
        <button class="button">
          <a href="{% url 'main:edit_ticket' object.pk %}">EDIT</a>
        </button>
        <button class="button">
          <a href="{% url 'main:delete_ticket' object.pk %}">DELETE</a>
        </button>
      </li>

      <hr />
      <!-- If object_list is empty  -->
      {% empty %}
      <li>No objects yet.</li>
      {% endfor %}
      
    </ul>
    {% else %}
    <p>Please login or Register</p>
    {% endif %}
    {% endblock %}
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

main/templates/login.html
{% extends "header.html" %}

{% block title %}
Login
{% endblock %}
{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

main/templates/logout.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome, {{user.username}}</a>
        </li>
  
        {% else %}
  
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
  
        {% endif %}
      </ul>
    </div>
  </nav>

main/templates/register.html
{% extends "header.html" %}
{% block title %}
Register
{% endblock %}
{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

main/templates/ticket_view.html
{% extends 'header.html'%}

{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<h1>{{object.name}}</h1>
<small>
    <p>{{object.pk}}</p>
    {% if user.is_authenticated %}
        <a href="{% url 'main:edit_ticket' object.pk %}">Edit</a>
        <a href="{% url 'main:delete_ticket' object.pk %}">Delete</a>
    {% endif %}
</small>

<br>
<hr>
{{object.description|safe}}
<hr>
<a href="{% url 'main:homepage' %}" class="btn btn-secondary">Back</a>
{% endblock %}

main/templates/update_ticket.html
{% extends 'header.html'%}
{% block title %}
Update Ticket | {{ticket.name}}
{% endblock %}
{% block content %}
<h1>Update Post</h1>
{% if user.is_authenticated or user.is_superuser %}
    <!-- <span>{{user.pk}} or  {{object.author.pk}}</span> -->
    {% if user.pk == object.author.pk or user.is_superuser %}
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-secondary">Update</button>
        </form>
    </div>
    {% else %}
    <p>You are not the currect user.</p> 
    {% endif %}
{% else %}
You Are Not Signed In. Please login or register to continue.
{% endif %}
{% endblock %}